// Implexus Powerlifting — change log (rolling 7-day window)
// Written automatically by scripts/scrape.mjs on each daily run.
// generated:      ISO timestamp of the run that produced this file.
// baselineDate:   when the current rank baseline was set (refreshed every 7 days).
// prevRankActive / prevRankAll: slug -> rank as of baselineDate, RE-RANKED over
//   the current roster so arrivals/departures don't create phantom arrows.
//   Position arrows compare current rank against these, so only genuine
//   lifting-driven movement shows — roster logistics net to zero.
// rosterActive / rosterAll: the slugs present at this run (roster-change basis).
// arrivals / departures:    who joined / left since the baseline (stored for
//   possible future use; not displayed). Arrivals show as NEW, not as movers.
// pbEvents:       personal-best improvements from the last 7 days, each stamped
//   with the date it hit the board. Shown as callout cards in dynamic mode,
//   ageing out after 7 days. A new PB for a lifter overrides their older one.

const CHANGES = {
  "generated": "2026-08-23T11:10:56.027Z",
  "baselineDate": "2026-08-22T11:10:10.907Z",
  "prevRankActive": {
    "wyliesung": 1,
    "mikejones1": 2,
    "genevievecollins": 3,
    "chrisjennings": 4,
    "benthornes": 5,
    "peterking1": 6,
    "anthonywhite1": 7,
    "nickjohnstone": 8,
    "taliafirth": 9,
    "ashlingkeeble": 10,
    "stevewhittles": 11,
    "williamwebb1": 12,
    "leemccafferty": 13,
    "tobysolomon": 14,
    "joecurzon": 15,
    "chloeboomer": 16,
    "matthewanderson2": 17,
    "owencrisp": 18,
    "johncousins1": 19,
    "robjacobs": 20,
    "jodiebarnsley": 21,
    "jacklarkinsthomas": 22,
    "laurajones6": 23
  },
  "prevRankAll": {
    "wyliesung": 1,
    "mikejones1": 2,
    "anneburns": 3,
    "maxguo": 4,
    "victoriahart": 5,
    "chrisonuoha": 6,
    "gerryleepierre": 7,
    "genevievecollins": 8,
    "chrisjennings": 9,
    "joshhinchcliffe": 10,
    "benthornes": 11,
    "karldaniel": 12,
    "kairichardson": 13,
    "peterking1": 14,
    "bradycrooks": 15,
    "anthonymclaughlin1": 16,
    "anthonywhite1": 17,
    "samriddharanjan": 18,
    "nickjohnstone": 19,
    "taliafirth": 20,
    "ashlingkeeble": 21,
    "stevewhittles": 22,
    "leohannan": 23,
    "williamwebb1": 24,
    "leemccafferty": 25,
    "alexshortland": 26,
    "tobysolomon": 27,
    "joecurzon": 28,
    "chloeboomer": 29,
    "finndavis": 30,
    "matthewanderson2": 31,
    "owencrisp": 32,
    "samlusher": 33,
    "johncousins1": 34,
    "robjacobs": 35,
    "roryturnbull": 36,
    "kellybroadbent": 37,
    "jodiebarnsley": 38,
    "jacklarkinsthomas": 39,
    "laurajones6": 40
  },
  "curRankActive": {
    "wyliesung": 1,
    "mikejones1": 2,
    "genevievecollins": 3,
    "chrisjennings": 4,
    "benthornes": 5,
    "peterking1": 6,
    "anthonywhite1": 7,
    "nickjohnstone": 8,
    "taliafirth": 9,
    "ashlingkeeble": 10,
    "stevewhittles": 11,
    "williamwebb1": 12,
    "leemccafferty": 13,
    "tobysolomon": 14,
    "joecurzon": 15,
    "chloeboomer": 16,
    "matthewanderson2": 17,
    "owencrisp": 18,
    "johncousins1": 19,
    "robjacobs": 20,
    "jodiebarnsley": 21,
    "jacklarkinsthomas": 22,
    "laurajones6": 23
  },
  "curRankAll": {
    "wyliesung": 1,
    "mikejones1": 2,
    "anneburns": 3,
    "maxguo": 4,
    "victoriahart": 5,
    "chrisonuoha": 6,
    "gerryleepierre": 7,
    "genevievecollins": 8,
    "chrisjennings": 9,
    "joshhinchcliffe": 10,
    "benthornes": 11,
    "karldaniel": 12,
    "kairichardson": 13,
    "peterking1": 14,
    "bradycrooks": 15,
    "anthonymclaughlin1": 16,
    "anthonywhite1": 17,
    "samriddharanjan": 18,
    "nickjohnstone": 19,
    "taliafirth": 20,
    "ashlingkeeble": 21,
    "stevewhittles": 22,
    "leohannan": 23,
    "williamwebb1": 24,
    "leemccafferty": 25,
    "alexshortland": 26,
    "tobysolomon": 27,
    "joecurzon": 28,
    "chloeboomer": 29,
    "finndavis": 30,
    "matthewanderson2": 31,
    "owencrisp": 32,
    "samlusher": 33,
    "johncousins1": 34,
    "robjacobs": 35,
    "roryturnbull": 36,
    "kellybroadbent": 37,
    "jodiebarnsley": 38,
    "jacklarkinsthomas": 39,
    "laurajones6": 40
  },
  "rosterActive": [
    "wyliesung",
    "mikejones1",
    "genevievecollins",
    "chrisjennings",
    "anthonywhite1",
    "nickjohnstone",
    "taliafirth",
    "stevewhittles",
    "williamwebb1",
    "ashlingkeeble",
    "joecurzon",
    "tobysolomon",
    "matthewanderson2",
    "owencrisp",
    "jodiebarnsley",
    "laurajones6",
    "jacklarkinsthomas",
    "peterking1",
    "benthornes",
    "robjacobs",
    "johncousins1",
    "leemccafferty",
    "chloeboomer"
  ],
  "rosterAll": [
    "wyliesung",
    "mikejones1",
    "genevievecollins",
    "chrisjennings",
    "anthonywhite1",
    "nickjohnstone",
    "taliafirth",
    "stevewhittles",
    "williamwebb1",
    "ashlingkeeble",
    "joecurzon",
    "tobysolomon",
    "matthewanderson2",
    "owencrisp",
    "jodiebarnsley",
    "laurajones6",
    "jacklarkinsthomas",
    "peterking1",
    "benthornes",
    "robjacobs",
    "johncousins1",
    "leemccafferty",
    "chloeboomer",
    "finndavis",
    "kairichardson",
    "leohannan",
    "samlusher",
    "chrisonuoha",
    "alexshortland",
    "kellybroadbent",
    "roryturnbull",
    "gerryleepierre",
    "karldaniel",
    "bradycrooks",
    "anthonymclaughlin1",
    "samriddharanjan",
    "anneburns",
    "maxguo",
    "victoriahart",
    "joshhinchcliffe"
  ],
  "arrivals": [],
  "departures": [],
  "pbEvents": [
    {
      "slug": "benthornes",
      "name": "Ben Thornes",
      "improved": {
        "deadlift": {
          "from": 315.5,
          "to": 317.5
        }
      },
      "dots": {
        "from": 453.92,
        "to": 453.92
      },
      "date": "2026-08-17T11:15:16.278Z"
    }
  ]
};
