// Implexus Powerlifting — Leaderboard Data
// PB squat, bench, deadlift and total from OpenPowerlifting Personal Bests table.
// For lifters with Raw + Wraps entries, best DOTS row determines ranking;
// individual lift PBs are taken across both equip categories.
// legacy: true = former member, shown only when legacy filter is on.
//
// This file is refreshed automatically every Wednesday by scripts/scrape.mjs.
// Add new lifters by hand; the scraper only updates lifters already listed.

const LIFTERS = [
  // ── ACTIVE MEMBERS ──────────────────────────────────────────
  {
    name: "Wylie Du Sung",
    slug: "wyliesung",
    ig: "wyliesung28",
    squat: 337.5, bench: 200, deadlift: 357.5, total: 890, dots: 562.53,
    fed: "GPU", equip: "Wraps", bodyweight: "94.3",
  },
  {
    name: "Mike Jones",
    slug: "mikejones1",
    ig: "mikejoneswigan",
    squat: 350, bench: 202.5, deadlift: 355, total: 902.5, dots: 535.63,
    fed: "GPU", equip: "Wraps", bodyweight: "109.4",
  },
  {
    name: "Jurassic Gen",
    slug: "genevievecollins",
    ig: "swole_mami",
    squat: 177.5, bench: 97.5, deadlift: 192.5, total: 467.5, dots: 466.15,
    fed: "EPA", equip: "Raw", bodyweight: "71.8",
  },
  {
    name: "Chris Jennings",
    slug: "chrisjennings",
    ig: "chris_implexus",
    squat: 202.5, bench: 140, deadlift: 245, total: 587.5, dots: 460.84,
    fed: "BP", equip: "Raw", bodyweight: "65.9",
  },
  {
    name: "Ant White",
    slug: "anthonywhite1",
    ig: "shred.kemper",
    squat: 250, bench: 137.5, deadlift: 280, total: 645, dots: 411.24,
    fed: "EPA", equip: "Raw", bodyweight: "92.6",
  },
  {
    name: "Nick Johnstone",
    slug: "nickjohnstone",
    ig: "njfullpower",
    squat: 247.5, bench: 180, deadlift: 242.5, total: 667.5, dots: 408.42,
    fed: "EPA", equip: "Raw", bodyweight: "101.4",
  },
  {
    name: "Talia Firth",
    slug: "taliafirth",
    ig: "talsssssx",
    squat: 177.5, bench: 102.5, deadlift: 187.5, total: 465, dots: 406.39,
    fed: "BPU", equip: "Wraps", bodyweight: "87.4",
  },
  {
    name: "Steve Whittles",
    slug: "stevewhittles",
    ig: "mrnorfgym",
    squat: 235, bench: 150, deadlift: 270, total: 650, dots: 395.43,
    fed: "WRPF-UK", equip: "Wraps", bodyweight: "102.8",
  },
  {
    name: "Will Webb",
    slug: "williamwebb1",
    ig: "willwebbpower",
    squat: 252.5, bench: 127.5, deadlift: 260, total: 630, dots: 385.53,
    fed: "BPU", equip: "Wraps", bodyweight: "98.6",
  },
  {
    name: "Ash Keeble",
    slug: "ashlingkeeble",
    ig: "ashlinglifts",
    squat: 155, bench: 90, deadlift: 167.5, total: 412.5, dots: 400.64,
    fed: "EPA", equip: "Raw", bodyweight: "75.4",
  },
  {
    name: "Joe Curzon",
    slug: "joecurzon",
    ig: "joecurzon93",
    squat: 242.5, bench: 125, deadlift: 250, total: 615, dots: 378.87,
    fed: "WRPF-UK", equip: "Wraps", bodyweight: "99.8",
  },
  {
    name: "Toby Solomon",
    slug: "tobysolomon",
    ig: "toby_solomon_",
    squat: 210, bench: 130, deadlift: 255, total: 595, dots: 383.66,
    fed: "EPA", equip: "Raw", bodyweight: "90.5",
  },
  {
    name: "Matt Anderson",
    slug: "matthewanderson2",
    ig: "mattslifts",
    squat: 160, bench: 110, deadlift: 215, total: 485, dots: 329.44,
    fed: "EPA", equip: "Raw", bodyweight: "82.1",
  },
  {
    name: "Owen Crisp",
    slug: "owencrisp",
    ig: "owen_crisp",
    squat: 172.5, bench: 102.5, deadlift: 202.5, total: 467.5, dots: 327.69,
    fed: "WRPF-UK", equip: "Raw", bodyweight: "76.5",
  },
  {
    name: "Jodie Barnsley",
    slug: "jodiebarnsley",
    ig: null,
    squat: 117.5, bench: 70, deadlift: 122.5, total: 307.5, dots: 295.36,
    fed: "WRPF-UK", equip: "Raw", bodyweight: "73.5",
  },
  {
    name: "Laura Jones",
    slug: "laurajones6",
    ig: "lauraelizabeth193",
    squat: 82.5, bench: 45, deadlift: 117.5, total: 245, dots: 245.62,
    fed: "WRPF-UK", equip: "Raw", bodyweight: "69.8",
  },
  {
    name: "Jack Larkins-Thomas",
    slug: "jacklarkinsthomas",
    ig: "jackliftingstuff",
    squat: 160, bench: 82.5, deadlift: 180, total: 422.5, dots: 245.91,
    fed: "WRPF-UK", equip: "Raw", bodyweight: "115.4",
  },
  {
    name: "Dr. Pete King",
    slug: "peterking1",
    ig: "kingpete__",
    squat: 220, bench: 155, deadlift: 270, total: 630, dots: 420.14,
    fed: "BPU", equip: "Raw", bodyweight: "84.8",
  },
  {
    name: "Ben Thornes",
    slug: "benthornes",
    ig: "wakefield_strength_academy",
    squat: 290, bench: 160, deadlift: 317.5, total: 752.5, dots: 453.92,
    fed: "BPU", equip: "Wraps", bodyweight: "104.9",
  },
  {
    name: "Rob Jacobs",
    slug: "robjacobs",
    ig: "Robj1190",
    squat: 195, bench: 97.5, deadlift: 200, total: 492.5, dots: 320.08,
    fed: "WRPF-UK", equip: "Raw", bodyweight: "89.1",
  },
  {
    name: "John Cousins",
    slug: "johncousins1",
    ig: null,
    squat: 165, bench: 125, deadlift: 192.5, total: 477.5, dots: 324.35,
    fed: "EPA", equip: "Raw", bodyweight: "82.1",
  },
  {
    name: "Lee McCafferty",
    slug: "leemccafferty",
    ig: "mccaff_strength_system",
    squat: 265, bench: 162.5, deadlift: 250, total: 677.5, dots: 385.41,
    fed: "WPC", equip: "Wraps", bodyweight: "123.5",
  },
  {
    name: "Chloe Boomer",
    slug: "chloeboomer",
    ig: "boomer_strength",
    squat: 122.5, bench: 62.5, deadlift: 155, total: 340, dots: 367.1,
    fed: "EPA", equip: "Raw", bodyweight: "62.6",
  },

  // ── LEGACY MEMBERS ──────────────────────────────────────────
  {
    name: "Finn Davis",
    slug: "finndavis",
    ig: "finndavispl",
    squat: 200, bench: 125, deadlift: 220, total: 545, dots: 347.84,
    fed: "EPA", equip: "Raw", bodyweight: "92.4",
    legacy: true,
  },
  {
    name: "Kai Richardson",
    slug: "kairichardson",
    ig: "koach_kai",
    squat: 215, bench: 145, deadlift: 300, total: 642.5, dots: 450.21,
    fed: "EPA", equip: "Raw", bodyweight: "76.9",
    legacy: true,
  },
  {
    name: "Leo Hannan",
    slug: "leohannan",
    ig: "leo.hannan",
    squat: 200, bench: 127.5, deadlift: 250, total: 572.5, dots: 388.07,
    fed: "EPA", equip: "Raw", bodyweight: "82.4",
    legacy: true,
  },
  {
    name: "Sam Lusher",
    slug: "samlusher",
    ig: "lush_sa94",
    squat: 205, bench: 142.5, deadlift: 215, total: 562.5, dots: 326.22,
    fed: "EPA", equip: "Raw", bodyweight: "116.6",
    legacy: true,
  },
  {
    name: "Chris Onuoha",
    slug: "chrisonuoha",
    ig: "chris_onu",
    squat: 280, bench: 150, deadlift: 340, total: 760, dots: 487.65,
    fed: "EPF", equip: "Raw", bodyweight: "91.4",
    legacy: true,
  },
  {
    name: "Alex Shortland",
    slug: "alexshortland",
    ig: "alex.shortland",
    squat: 240, bench: 155, deadlift: 270, total: 665, dots: 383.8,
    fed: "BPU", equip: "Wraps", bodyweight: "118.2",
    legacy: true,
  },
  {
    name: "Kelly Shortland",
    slug: "kellybroadbent",
    ig: null,
    squat: 105, bench: 47.5, deadlift: 150, total: 295, dots: 307.61,
    fed: "EPA", equip: "Raw", bodyweight: "66.3",
    legacy: true,
  },
  {
    name: "Rory Turnbull",
    slug: "roryturnbull",
    ig: "rpturnbull",
    squat: 170, bench: 112.5, deadlift: 230, total: 512.5, dots: 314.64,
    fed: "EPA", equip: "Raw", bodyweight: "100.6",
    legacy: true,
  },
  {
    name: "Gerry-Lee Pierre",
    slug: "gerryleepierre",
    ig: "gerryleepierre",
    squat: 305, bench: 182.5, deadlift: 305, total: 785, dots: 483.49,
    fed: "BPU", equip: "Wraps", bodyweight: "99.8",
    legacy: true,
  },
  {
    name: "Karl Daniel",
    slug: "karldaniel",
    ig: "only_2_ks",
    squat: 240, bench: 160, deadlift: 300, total: 700, dots: 452.62,
    fed: "BPU", equip: "Wraps", bodyweight: "90",
    legacy: true,
  },
  {
    name: "Brady Crooks",
    slug: "bradycrooks",
    ig: null,
    squat: 245, bench: 152.5, deadlift: 255, total: 652.5, dots: 415.15,
    fed: "EPA", equip: "Raw", bodyweight: "93",
    legacy: true,
  },
  {
    name: "Tony McLaughlin",
    slug: "anthonymclaughlin1",
    ig: "fat_tony2",
    squat: 245, bench: 152.5, deadlift: 300, total: 680, dots: 411.38,
    fed: "EPA", equip: "Raw", bodyweight: "104.2",
    legacy: true,
  },
  {
    name: "Dr. Samriddha Ranjan",
    slug: "samriddharanjan",
    ig: "riddhiculous.strength",
    squat: 220, bench: 127.5, deadlift: 242.5, total: 582.5, dots: 408.87,
    fed: "BP", equip: "Raw", bodyweight: "73",
    legacy: true,
  },
  {
    name: "Annie Burns",
    slug: "anneburns",
    ig: "anneinthegym",
    squat: 177.5, bench: 105, deadlift: 195, total: 477.5, dots: 521.22,
    fed: "IPF", equip: "Raw", bodyweight: "61.5",
    legacy: true,
  },
  {
    name: "Max Guo",
    slug: "maxguo",
    ig: "maxguo83kg",
    squat: 255, bench: 177.5, deadlift: 287.5, total: 720, dots: 488.39,
    fed: "BP", equip: "Raw", bodyweight: "82.3",
    legacy: true,
  },
  {
    name: "Vic Hart",
    slug: "victoriahart",
    ig: "vicsquats_",
    squat: 175, bench: 102.5, deadlift: 172.5, total: 450, dots: 488.26,
    fed: "BP", equip: "Raw", bodyweight: "62.1",
    legacy: true,
  },
  {
    name: "Josh Hinchcliffe",
    slug: "joshhinchcliffe",
    ig: "josh_hinchcliffe_pl",
    squat: 232.5, bench: 160, deadlift: 280, total: 670, dots: 456.45,
    fed: "PWFL", equip: "Raw", bodyweight: "81.6",
    legacy: true,
  },

];
